spring:
  application:
    name: common-gateway
  cloud:
    consul:
      config:
        defaultContext: ${spring.application.name}
        format: yaml
        prefixes: config
  main:
    web-application-type: reactive
---
spring:
  cloud:
    consul:
      host: localhost
  config:
    activate:
      on-profile: pro
    import: optional:consul:localhost:8500
---
spring:
  cloud:
    consul:
      host: 192.168.1.94
  config:
    activate:
      on-profile: test
    import: optional:consul:192.168.1.94:8500
---
spring:
  cloud:
    consul:
      config:
        acl-token: 877ceaf8-e219-8474-dbb5-f92200235f92
      host: 192.168.160.8
  config:
    activate:
      on-profile: dev
    import: optional:consul:192.168.160.8:8500
