spring:
  application:
    name: common-gateway
  cloud:
    consul:
      config:
        defaultContext: ${spring.application.name}
        format: yaml
        prefixes: config
---
spring:
  cloud:
    consul:
      host: localhost
  config:
    activate:
      on-profile: pro
    import: optional:consul:localhost:8500
---
spring:
  cloud:
    consul:
      host: localhost
  config:
    activate:
      on-profile: test
    import: optional:consul:localhost:8500
---
spring:
  cloud:
    consul:
      host: 192.168.160.8
    inetutils:
      preferred-networks: 192\.168\.[\d]+\.[\d]+
  config:
    activate:
      on-profile: dev
    import: optional:consul:192.168.160.8:8500